import Link from "next/link";
import { VectorSketch } from "@/components/VectorSketch";
import { SiteNav } from "@/components/SiteNav";
import { LegalNav } from "@/components/LegalNav";

export const metadata = { title: "Terms of Service — ZeroFans" };

// Terms of Service. MVP-grade but real and specific — payment processors and
// merchants of record require a genuine ToS describing the service, acceptable
// use, payment terms, and liability before they approve an account.
export default function Terms() {
  return (
    <>
      <VectorSketch variant="alt" />
      <div className="relative z-10 flex min-h-screen flex-col">
        <SiteNav />
        <main className="mx-auto w-full max-w-2xl px-6 pb-20 pt-4">
          <header className="panel mb-8 px-8 pb-7 pt-6">
            <div className="mb-3 flex items-center justify-between text-xs uppercase tracking-widest text-ink-subtle">
              <span>Terms of Service</span>
              <span>ZeroFans Labs</span>
            </div>
            <div className="receipt-rule mb-5" />
            <h1 className="pixel text-ink" style={{ fontSize: "clamp(26px,3.4vw,38px)" }}>
              Terms of Service
            </h1>
            <p className="mt-3 text-sm text-ink-subtle">
              Last updated {new Date().toLocaleDateString()}.
            </p>
          </header>

          <LegalNav active="terms" />

          <div className="mt-8 space-y-9 text-sm leading-relaxed text-ink-muted">
            <Section title="1. What ZeroFans is">
              <p>
                ZeroFans analyzes a product URL you submit and returns a ranked
                map of online communities where you might launch it, along with
                each community&apos;s public rules, posting guidance, suggested
                timing, and optional AI-generated post drafts. ZeroFans is an
                information and drafting tool only.
              </p>
            </Section>

            <Section title="2. No automated posting">
              <p>
                ZeroFans never posts on your behalf. Every submission to any
                third-party community is performed manually by you. You are
                solely responsible for complying with each community&apos;s rules
                and terms when you post.
              </p>
            </Section>

            <Section title="3. Acceptable use">
              <ul className="list-disc space-y-1.5 pl-5">
                <li>Do not use ZeroFans for spam, harassment, or illegal content.</li>
                <li>Do not submit URLs or content you don&apos;t have the right to use.</li>
                <li>Do not attempt to bypass usage limits, scrape, or abuse the API.</li>
                <li>One account per person; don&apos;t resell access.</li>
              </ul>
            </Section>

            <Section title="4. Accounts">
              <p>
                You sign in with GitHub. You are responsible for activity under
                your account. We may suspend accounts that violate these terms.
              </p>
            </Section>

            <Section title="5. Plans, payments & limits">
              <p>
                Free accounts may generate a limited number of maps per day. Paid
                plans raise that limit and unlock the full community list and
                drafts. Prices are shown before purchase. Payments are processed
                by our third-party payment provider; by purchasing you also agree
                to their terms. See our{" "}
                <Link href="/refunds" className="text-primary hover:underline">
                  Refund &amp; Cancellation Policy
                </Link>
                .
              </p>
            </Section>

            <Section title="6. AI-generated content">
              <p>
                Draft posts are generated by AI as a starting point and may be
                inaccurate or generic. You must review and adapt them before
                posting. Community rules can change; verify them yourself before
                relying on our data.
              </p>
            </Section>

            <Section title="7. Disclaimers & liability">
              <p>
                The service is provided “as is”, without warranties. ZeroFans is
                not responsible for the outcome of any post you make, for bans or
                removals by third-party communities, or for indirect or
                consequential damages. Our total liability is limited to the
                amount you paid in the prior 12 months.
              </p>
            </Section>

            <Section title="8. Changes & contact">
              <p>
                We may update these terms; material changes will be reflected by
                the date above. Questions:{" "}
                <Link href="/contact" className="text-primary hover:underline">
                  contact us
                </Link>
                .
              </p>
            </Section>
          </div>
        </main>
      </div>
    </>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="eyebrow mb-3 text-ink">{title}</h2>
      {children}
    </section>
  );
}
