import type { Community, ProductAnalysis } from "./types";
import { rankCommunities } from "./matching";

// Mock catalog so the map UI is viewable on localhost before Supabase is wired.
// ⚠️ Mirrors supabase/seed.sql — keep the two in sync until Stage 1 loads the
// real DB (then /demo can query Postgres and this file goes away).
// Ranking below uses the REAL matcher (lib/matching.ts), not hand-set scores.

const COMMUNITIES: Community[] = [
  c(1, "reddit", "r/SideProject", "https://www.reddit.com/r/SideProject/",
    ["saas", "indie", "vibecoders", "sideproject", "ai", "webapp", "launch", "buildinpublic"],
    "welcome", "Sharing what you built is the point of the sub (~628K). Reddit drives 3-8x more indie signups than Product Hunt.",
    "Removed: bare links / no context. Required: what it is, why, tech, what feedback you want.",
    "easy", "New accounts tolerated; comment a few days first.", "active", "Tue-Thu 9-12 ET"),
  c(2, "reddit", "r/indiehackers", "https://www.reddit.com/r/indiehackers/",
    ["indie", "bootstrapped", "saas", "solofounder", "buildinpublic", "launch", "microsaas"],
    "welcome", "Showcase community (~100K). Best format: \"Launched X months ago, Y users — here's what I learned.\"",
    "Required: genuine journey posts with real numbers. Removed: pure promo with no story.",
    "easy", "Low barrier.", "moderate", "Tue-Thu mornings ET"),
  c(3, "reddit", "r/microsaas", "https://www.reddit.com/r/microsaas/",
    ["microsaas", "saas", "indie", "bootstrapped", "solofounder", "launch", "b2b"],
    "welcome", "Build-in-public and small-launch posts welcome when they add insight.",
    "Required: share numbers / learnings, not just a link.",
    "easy", "Low barrier; some account age helps.", "moderate", "Tue-Thu 10-13 ET"),
  c(4, "reddit", "r/alphaandbetausers", "https://www.reddit.com/r/alphaandbetausers/",
    ["beta", "earlyaccess", "feedback", "indie", "testers", "launch"],
    "welcome", "Purpose-built for recruiting early users / testers.",
    "Required: label stage (alpha/beta) and the exact feedback you want.",
    "easy", "Minimal karma needs.", "low", "Any weekday morning ET"),
  c(5, "reddit", "r/roastmystartup", "https://www.reddit.com/r/roastmystartup/",
    ["feedback", "startup", "indie", "saas", "launch", "critique"],
    "welcome", "Feedback-first — you post to get torn apart constructively.",
    "Required: be ready for blunt critique; ask specific questions.",
    "easy", "Low barrier.", "moderate", "Weekday mornings ET"),
  c(6, "reddit", "r/IMadeThis", "https://www.reddit.com/r/IMadeThis/",
    ["indie", "sideproject", "webapp", "launch", "showcase", "maker"],
    "welcome", "Showcase what you personally made.",
    "Required: it must be something you built; show the thing.",
    "easy", "Low barrier.", "moderate", "Tue-Thu ET"),
  c(7, "reddit", "r/vibecoding", "https://www.reddit.com/r/vibecoding/",
    ["ai", "vibecoders", "devtool", "aicoding", "indie", "launch", "webapp"],
    "welcome", "Newer community for AI-assisted builders — your exact ICP.",
    "Required: tie the post to the AI / vibe-coding workflow.",
    "easy", "Low barrier; growing fast.", "active", "Weekdays, midday ET"),
  c(8, "reddit", "r/EntrepreneurRideAlong", "https://www.reddit.com/r/EntrepreneurRideAlong/",
    ["startup", "founder", "indie", "saas", "buildinpublic", "journey"],
    "welcome", "Journey / build-along community — narrative posts do well.",
    "Required: share the process and lessons.",
    "medium", "Some history expected.", "moderate", "Mon-Wed ET"),
  c(9, "reddit", "r/SaaS", "https://www.reddit.com/r/SaaS/",
    ["saas", "b2b", "indie", "startup", "launch", "pricing"],
    "megathread_only", "Use the weekly \"Share Your SaaS\" / feedback threads.",
    "Removed: standalone launch posts; name+link+one-liner = spam.",
    "medium", "Brand-new accounts often filtered.", "active", "Mon-Wed 8-11 ET"),
  c(10, "reddit", "r/startups", "https://www.reddit.com/r/startups/",
    ["startup", "saas", "founder", "launch", "feedback", "b2b"],
    "megathread_only", "Use \"Share Your Startup\" / Feedback Friday threads.",
    "Removed: self-promo in the main feed.",
    "medium", "Account age + comment karma expected.", "active", "Fri (Feedback Friday) ET"),
  c(11, "reddit", "r/Entrepreneur", "https://www.reddit.com/r/Entrepreneur/",
    ["startup", "business", "founder", "saas", "marketing"],
    "megathread_only", "Strict; product mentions must emerge from valuable content.",
    "Removed: \"check out my product\" posts. Norm: 10:1 helpful-to-promo.",
    "hard", "Established account + comment karma recommended.", "active", "Mon/Thu 9-12 ET"),
  c(12, "reddit", "r/webdev", "https://www.reddit.com/r/webdev/",
    ["webdev", "devtool", "saas", "frontend", "launch", "showcase"],
    "megathread_only", "Showcase only in the weekly \"Showoff Saturday\" thread.",
    "Removed: self-promo outside Showoff Saturday.",
    "medium", "Some history expected.", "active", "Sat (Showoff Saturday) ET"),
  c(13, "directory", "Product Hunt", "https://www.producthunt.com/posts/new",
    ["launch", "saas", "devtool", "ai", "startup", "webapp"],
    "welcome", "24h launch spike, broad tech audience (~300-1k visits/day). Relaunch after 6 months.",
    "Required: prep assets + a hunter/network; pick a day; engage all day.",
    "easy", "No karma; success = prep + day-of engagement.", "active", "Tue-Thu 00:01 PT"),
  c(14, "hackernews", "Hacker News — Show HN", "https://news.ycombinator.com/showhn.html",
    ["devtool", "opensource", "saas", "ai", "launch", "technical"],
    "megathread_only", "Show HN is the place for something you built. 100% builder audience.",
    "Required: modest tone, NO superlatives, go deep on details.",
    "hard", "Account needed; quality + honesty rule.", "active", "Early week, mornings PT"),
  c(15, "directory", "BetaList", "https://betalist.com/submit",
    ["beta", "earlyaccess", "startup", "waitlist", "saas", "launch"],
    "welcome", "Pre-launch waitlist directory, strong email base. Free but low acceptance.",
    "Required: submit via form; only well-presented products get the free slot.",
    "easy", "No karma; editorial bar.", "moderate", "N/A — submission-based"),
  c(16, "directory", "Peerlist Launchpad", "https://peerlist.io/launchpad",
    ["launch", "saas", "devtool", "indie", "maker", "professional"],
    "welcome", "Professional builder network. One product/week, week-long competition.",
    "Required: complete product profile; weekly slot.",
    "easy", "No karma; complete profile helps.", "moderate", "Submit Monday"),
  c(17, "directory", "Uneed", "https://www.uneed.best/submit-a-tool",
    ["devtool", "saas", "ai", "directory", "launch"],
    "welcome", "Curated tool directory. Free with a waiting period; $30 to skip.",
    "Required: submit via form; curated, quality matters.",
    "easy", "No karma; editorial curation.", "moderate", "N/A — submission-based"),
  c(18, "directory", "MicroLaunch", "https://microlaunch.net/",
    ["launch", "indie", "saas", "microsaas", "devtool"],
    "welcome", "PH-style but live for a month — no 24h upvote pressure. Free.",
    "Required: submit; supportive community.",
    "easy", "No karma.", "moderate", "N/A — month-long"),
  c(19, "directory", "DevHunt", "https://devhunt.org/",
    ["devtool", "cli", "api", "opensource", "launch", "technical"],
    "welcome", "\"Product Hunt for developers\" — 100% dev audience.",
    "Required: must be a developer tool; submit via form.",
    "easy", "No karma.", "moderate", "Weekly cycle"),
  c(20, "directory", "Indie Hackers", "https://www.indiehackers.com/",
    ["indie", "bootstrapped", "saas", "solofounder", "buildinpublic", "launch"],
    "welcome", "Bootstrapped-founder community; PH-style exposure, less competition.",
    "Required: post in the right group, lead with the story / lessons.",
    "easy", "No karma gate.", "moderate", "Tue-Thu mornings ET"),
];

// Helper keeps each row to one line above.
function c(
  id: number,
  platform: Community["platform"],
  name: string,
  url: string,
  niche_tags: string[],
  self_promo_policy: Community["self_promo_policy"],
  self_promo_note: string,
  rules_summary: string,
  karma_tier: Community["karma_tier"],
  karma_note: string,
  activity_level: Community["activity_level"],
  best_time: string
): Community {
  return {
    id, platform, name, url, niche_tags, self_promo_policy, self_promo_note,
    rules_summary, karma_tier, karma_note, activity_level, best_time,
    submit_template: null, verified_at: "2026-06-17",
  };
}

export const DEMO_ANALYSIS: ProductAnalysis = {
  product_summary: "An AI tool that turns your product URL into a ranked launch map",
  category: "Developer tool / SaaS",
  icp: "indie makers and vibe-coders with zero audience",
  niche_tags: ["saas", "indie", "launch", "vibecoders", "ai", "devtool"],
};

// Ranked via the real matcher — top 4 unlocked, rest locked (free-tier split).
export const DEMO_RANKED = rankCommunities(DEMO_ANALYSIS, COMMUNITIES, false);
