#!/usr/bin/env node
// Generate supabase/seed.sql from data/communities.json.
//
// data/communities.json is the SINGLE SOURCE OF TRUTH for the community catalog.
// Edit the JSON → run `npm run db:seed-gen` → load the generated SQL to Supabase.
// The script validates every row first, so a typo can't silently ship bad data
// (which, per the spec, = a banned user).
//
// Usage: node scripts/gen-seed.mjs   (or: npm run db:seed-gen)

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SRC = join(ROOT, "data", "communities.json");
const OUT = join(ROOT, "supabase", "seed.sql");

const PLATFORMS = ["reddit", "discord", "x", "hackernews", "directory"];
const POLICIES = ["welcome", "megathread_only", "comment_only", "banned"];
const KARMA = ["easy", "medium", "hard", null];
const ACTIVITY = ["active", "moderate", "low", null];
const DATE_RE = /^\d{4}-\d{2}-\d{2}$/;
const STALE_DAYS = 45; // warn when a row hasn't been re-verified recently

function fail(msg) {
  console.error(`\x1b[31m[gen-seed] ${msg}\x1b[0m`);
  process.exit(1);
}

const rows = JSON.parse(readFileSync(SRC, "utf8"));
if (!Array.isArray(rows)) fail("communities.json must be an array");

// ── Validate every row ──────────────────────────────────────────
const seenIds = new Set();
const seenUrls = new Set();
const warnings = [];
const today = new Date();

rows.forEach((r, i) => {
  const where = `row ${i} (${r.name ?? "?"})`;
  if (typeof r.id !== "number") fail(`${where}: id must be a number`);
  if (seenIds.has(r.id)) fail(`${where}: duplicate id ${r.id}`);
  seenIds.add(r.id);
  if (!r.name) fail(`${where}: name required`);
  if (!/^https?:\/\//.test(r.url || "")) fail(`${where}: url must be http(s)`);
  if (seenUrls.has(r.url)) warnings.push(`${where}: duplicate url ${r.url}`);
  seenUrls.add(r.url);
  if (!PLATFORMS.includes(r.platform)) fail(`${where}: bad platform "${r.platform}"`);
  if (!POLICIES.includes(r.self_promo_policy)) fail(`${where}: bad self_promo_policy`);
  if (!KARMA.includes(r.karma_tier ?? null)) fail(`${where}: bad karma_tier`);
  if (!ACTIVITY.includes(r.activity_level ?? null)) fail(`${where}: bad activity_level`);
  if (!Array.isArray(r.niche_tags) || r.niche_tags.length === 0)
    fail(`${where}: niche_tags must be a non-empty array`);
  if (!DATE_RE.test(r.verified_at || "")) fail(`${where}: verified_at must be YYYY-MM-DD`);

  // Freshness warning — the moat decays. Surface stale rows, don't block.
  const age = Math.floor((today - new Date(r.verified_at)) / 86_400_000);
  if (age > STALE_DAYS) warnings.push(`${where}: verified_at is ${age} days old — re-verify`);
});

// ── Emit SQL ────────────────────────────────────────────────────
const q = (v) => (v == null ? "null" : `'${String(v).replace(/'/g, "''")}'`);
const arr = (a) => `'{${a.map((t) => `"${String(t).replace(/"/g, '\\"')}"`).join(",")}}'`;

const num = (v) => (v == null ? "null" : String(Math.round(Number(v))));

const values = rows
  .map(
    (r) =>
      `  (${q(r.platform)}, ${q(r.name)}, ${q(r.url)}, ${arr(r.niche_tags)},\n` +
      `   ${q(r.self_promo_policy)}, ${q(r.self_promo_note)},\n` +
      `   ${q(r.rules_summary)}, ${q(r.karma_tier)}, ${q(r.karma_note)},\n` +
      `   ${q(r.activity_level)}, ${q(r.best_time)}, ${q(r.submit_template)}, ${q(r.verified_at)}, ${num(r.members)}, ${q(r.icon)})`
  )
  .join(",\n");

const sql = `-- AUTO-GENERATED by scripts/gen-seed.mjs from data/communities.json.
-- DO NOT EDIT BY HAND — edit data/communities.json then run \`npm run db:seed-gen\`.
--
-- ⚠️ Accuracy principle (spec): rules change. data/communities.json carries
-- verified_at per row; re-verify against live sidebars before production and
-- monthly thereafter. The generator warns on rows older than ${STALE_DAYS} days.
--
-- Rows: ${rows.length} | Generated: ${today.toISOString().slice(0, 10)}

truncate table communities restart identity cascade;

insert into communities
  (platform, name, url, niche_tags, self_promo_policy, self_promo_note,
   rules_summary, karma_tier, karma_note, activity_level, best_time,
   submit_template, verified_at, members, icon)
values
${values};
`;

writeFileSync(OUT, sql, "utf8");

console.log(`\x1b[32m[gen-seed] wrote ${rows.length} rows → supabase/seed.sql\x1b[0m`);
if (warnings.length) {
  console.log("\x1b[33m[gen-seed] warnings:\x1b[0m");
  warnings.forEach((w) => console.log(`  - ${w}`));
}
